// default package
// Generated 24/12/2016 10:08:45 AM by Hibernate Tools 5.1.0.Alpha1
package co.srsp.hibernate.orm;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CompanyPositions generated by hbm2java
 */
public class CompanyPositions implements java.io.Serializable {

	private Integer idcompanyPositions;
	private String positionName;
	private String positionImportance;
	private Date fromDate;
	private Date toDate;
	private Set employees = new HashSet(0);

	public CompanyPositions() {
	}

	public CompanyPositions(String positionName, String positionImportance, Date fromDate) {
		this.positionName = positionName;
		this.positionImportance = positionImportance;
		this.fromDate = fromDate;
	}

	public CompanyPositions(String positionName, String positionImportance, Date fromDate, Date toDate, Set employees) {
		this.positionName = positionName;
		this.positionImportance = positionImportance;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.employees = employees;
	}

	public Integer getIdcompanyPositions() {
		return this.idcompanyPositions;
	}

	public void setIdcompanyPositions(Integer idcompanyPositions) {
		this.idcompanyPositions = idcompanyPositions;
	}

	public String getPositionName() {
		return this.positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	public String getPositionImportance() {
		return this.positionImportance;
	}

	public void setPositionImportance(String positionImportance) {
		this.positionImportance = positionImportance;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
