// default package
// Generated 24/12/2016 10:08:45 AM by Hibernate Tools 5.1.0.Alpha1

package co.srsp.hibernate.orm;

/**
 * EmployeeToSkillsetRatings generated by hbm2java
 */
public class EmployeeToSkillsetRatings implements java.io.Serializable {

	private Integer idemployeeToSkillsetRatings;
	private Employee employee;
	private EmployeeSkillset employeeSkillset;

	public EmployeeToSkillsetRatings() {
	}

	public EmployeeToSkillsetRatings(Employee employee, EmployeeSkillset employeeSkillset) {
		this.employee = employee;
		this.employeeSkillset = employeeSkillset;
	}

	public Integer getIdemployeeToSkillsetRatings() {
		return this.idemployeeToSkillsetRatings;
	}

	public void setIdemployeeToSkillsetRatings(Integer idemployeeToSkillsetRatings) {
		this.idemployeeToSkillsetRatings = idemployeeToSkillsetRatings;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public EmployeeSkillset getEmployeeSkillset() {
		return this.employeeSkillset;
	}

	public void setEmployeeSkillset(EmployeeSkillset employeeSkillset) {
		this.employeeSkillset = employeeSkillset;
	}

}
