// default package
// Generated 24/12/2016 10:08:45 AM by Hibernate Tools 5.1.0.Alpha1
package co.srsp.hibernate.orm;

import java.util.HashSet;
import java.util.Set;

/**
 * OrgDepartment generated by hbm2java
 */
public class OrgDepartment implements java.io.Serializable {

	private Integer idorgDepartment;
	private String deptName;
	private String location;
	private Set employees = new HashSet(0);

	public OrgDepartment() {
	}

	public OrgDepartment(String deptName) {
		this.deptName = deptName;
	}

	public OrgDepartment(String deptName, String location, Set employees) {
		this.deptName = deptName;
		this.location = location;
		this.employees = employees;
	}

	public Integer getIdorgDepartment() {
		return this.idorgDepartment;
	}

	public void setIdorgDepartment(Integer idorgDepartment) {
		this.idorgDepartment = idorgDepartment;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

}
