// default package
// Generated 24/12/2016 10:08:45 AM by Hibernate Tools 5.1.0.Alpha1
package co.srsp.hibernate.orm;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer usersId;
	private String username;
	private String password;
	private String enabled;

	public Users() {
	}

	public Users(String username, String password, String enabled) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
	}

	public Integer getUsersId() {
		return this.usersId;
	}

	public void setUsersId(Integer usersId) {
		this.usersId = usersId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

}
