// default package
// Generated 24/12/2016 10:08:45 AM by Hibernate Tools 5.1.0.Alpha1
package co.srsp.hibernate.orm;

/**
 * UserRoles generated by hbm2java
 */
public class UserRoles implements java.io.Serializable {

	private UserRolesId id;

	public UserRoles() {
	}

	public UserRoles(UserRolesId id) {
		this.id = id;
	}

	public UserRolesId getId() {
		return this.id;
	}

	public void setId(UserRolesId id) {
		this.id = id;
	}

}
