// default package
// Generated 24/12/2016 10:08:45 AM by Hibernate Tools 5.1.0.Alpha1
package co.srsp.hibernate.orm;

/**
 * UserRolesId generated by hbm2java
 */
public class UserRolesId implements java.io.Serializable {

	private int userRoleId;
	private String username;
	private String role;

	public UserRolesId() {
	}

	public UserRolesId(int userRoleId, String username, String role) {
		this.userRoleId = userRoleId;
		this.username = username;
		this.role = role;
	}

	public int getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(int userRoleId) {
		this.userRoleId = userRoleId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRolesId))
			return false;
		UserRolesId castOther = (UserRolesId) other;

		return (this.getUserRoleId() == castOther.getUserRoleId())
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null && castOther.getRole() != null
						&& this.getRole().equals(castOther.getRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserRoleId();
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getRole() == null ? 0 : this.getRole().hashCode());
		return result;
	}

}
